# Generated by Django 2.2 on 2019-04-26 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notes', models.TextField()),
                ('attendee', models.ManyToManyField(related_name='attendees', to='users.User')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='users.User')),
            ],
        ),
    ]
