# Generated by Django 2.2 on 2019-04-26 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20190425_1746'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='spot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='map.Marker'),
            preserve_default=False,
        ),
    ]
