# Generated by Django 2.2 on 2019-04-25 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
        ('map', '0002_auto_20190423_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marker',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creators', to='users.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marker',
            name='level',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marker',
            name='notes',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='lat',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='marker',
            name='lng',
            field=models.CharField(max_length=255),
        ),
    ]
