# Generated by Django 2.2 on 2019-04-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20190425_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='level',
        ),
        migrations.AddField(
            model_name='marker',
            name='score',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='marker',
            name='vites',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
