# Generated by Django 2.2 on 2019-04-26 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20190425_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='vites',
            new_name='votes',
        ),
    ]
